### ISSUE TITLE
Issue Importing acropalypse_gif module

### ISSUE THREAD

**Issue by Sbike** [frankthetank-music/Acropalypse-Multi-Tool#1]
Hi, when running `python gui.py` after installing the required pip install, I got the following error. 
```
\Desktop\Acropalypse-Multi-Tool-main\Acropalypse-Multi-Tool-main>python gui.py
Traceback (most recent call last):
  File "gui.py", line 15, in <module>
    from gif_lib import acropalypse_gif
ImportError: DLL load failed: The specified module could not be found.
```

I managed to use the tool to recover a windows 11 image by commenting the concerned import line in gui.py file as the following. The gui is starting and the feature I used was working well.
```
#begginning of the gui.py file
#from gif_lib import acropalypse_gif
#end of the file
```
Thanks for reading, have a nice day

**Comment by frankthetank-music** [comment]
Hello,

Thank you for reaching out with your issue. It seems that you have encountered a DLL load failure when trying to import a module in your Python project. This error can often occur due to an incompatible Python version with the required native binaries of the package you're trying to import.

The acropalypse_gif module relies on compiled binaries that are not compatible with your installed version of Python. As you have noted, commenting out the import allows the GUI to start and other features to work, but all features related to this module won't work.

As this was a project at university, there is no update to newer python versions planned, but here are a couple of solutions you could try:

**Switch to Python 3.10:** acropalypse_gif was compiled against Python 3.10 and thus would require you to run your script with that specific version of Python. Make sure to use this version when running your script.

**Use the Prebuilt Docker Container:** There is a Docker container available for this project, it contains all the necessary dependencies and configurations already set up for you. Using Docker could bypass the compatibility issues by providing a consistent environment that's been pre-configured.

On Linux run:
```
xhost +local:
sudo docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix frankthetankmusic/acropalypse-multi-tool
```

**Run on Linux:** If you have access to a Linux environment, try running your program there. Often, dependencies and binaries are more straightforward to manage and install on Linux, and you may find that the acropalypse_gif module and its dependencies are more Linux-friendly. Also the Docker Container is easier to use on Linux, as there are difficulties using the X-Server on Windows.

Hope this helps, and if you need further assistance, feel free to ask.

Have a great day!

**Comment by Sbike** [comment]
Hello, thank you for your accurate reply and for adding the docker feature !
